services:
  # 🐰 RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: desafioGDASH_rabbitmq
    restart: always
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    # Portas definidas no override. Aqui se for prod

  # 🍃 MongoDB (Banco de Dados)
  mongodb:
    image: mongo:latest
    container_name: desafioGDASH_mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  # 🐍 Weather Collector (Python)
  weather-collector:
    build:
      context: ./collector-weather
      dockerfile: Dockerfile
    container_name: desafioGDASH_collector_weather
    depends_on:
      - rabbitmq
    env_file: .env

  # 🐹 Worker (Go)
  weather-worker:
    build:
      context: ./worker-weather
      dockerfile: Dockerfile
    container_name: desafioGDASH_worker_weather
    depends_on:
      - rabbitmq
      - mongodb # quando for usar mongo cai precisar
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  backend:
    build:
      context: ./backend-api
      dockerfile: dockerfile
    container_name: desafioGDASH_backend
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@desafiogdash.p6dv8be.mongodb.net/?appName=desafioGDASH
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: desafioGDASH_frontend
    depends_on:
      - backend

volumes:
  mongodb_data:
  rabbitmq_data:
