services:
  # Expondo portas
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./collector-weather:/app
      - ./worker-weather:/app

  mongodb:
    ports:
      - "${MONGO_PORT}:27017"
