services:
  weather-collector:
    volumes:
      - ./collector-weather:/app
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend:
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend-api:/app
      - /app/node_modules
      - ./uploads:/app/uploads
  
  frontend:
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
